In [1]:
import pandas as pd

In [ ]:
num = int(input())

result = ""
n = 1
while n <= num:
    result += str(n ** 2) + " "
    n += 1

print(result)

3
1 4 9

In [ ]:
num = int(input())

i = 1

summa_nums = 0

while i <= num:
  summa_nums += i
  i += 1
print(summa_nums)

5
10

1.3.3. Тренажер кода 1
Напишите программу, которая:
Просит пользователя ввести через пробел список оценок студента за семестр (например, 5 4 3 5 4).
Преобразует введённые данные в список целых чисел.
Вычисляет средний балл студента.
Находит все оценки, которые выше среднего балла, и выводит их.

Создайте базовый класс Employee (Сотрудник) со следующими атрибутами и методами:

Атрибуты:

name - имя сотрудника
salary - зарплата
Методы:

work() - выводит на экран сообщение: "Работаю"
take_break() - выводит на экран сообщение: "Отдыхаю"

In [ ]:
class Employee:
  def __init__(self, name, salary) -> None:
    self.name = name
    self.salary = salary

  def work(self):
    print("Работаю")

  def take_break(self):
    print("Отдыхаю")

class Developer(Employee):
  def __init__(self, name, salary, programming_language) -> None:
     self.programming_language = programming_language
     super().__init__(name, salary)

  def write_code(self):
    print("Пишу код")

if __name__ == "__main__":
    empl = Employee("Egor", 6000)
    dev = Developer("Egor", 6000, "Python")
    empl.work()
    empl.take_break()
    dev.write_code()

Работаю
Отдыхаю
Пишу код

In [ ]:
alice_hobbies = {"рисование", "программирование", "чтение", "йога"}
marusya_hobbies = {"фотография", "программирование", "йога", "путешествия"}

print(f"Общие увлечения: {alice_hobbies & marusya_hobbies}")
print(f"Только у Алисы: {alice_hobbies - marusya_hobbies}")
print(f"Все увлечения: {alice_hobbies | marusya_hobbies}")

hobby = "плавание"
if hobby in alice_hobbies | marusya_hobbies:
    print(f"'{hobby}' есть у кого-то из друзей")
else:
    print(f"'{hobby}' нет ни у кого")

Общие увлечения: {'йога', 'программирование'}
Только у Алисы: {'чтение', 'рисование'}
Все увлечения: {'рисование', 'путешествия', 'чтение', 'программирование', 'фотография', 'йога'}
'плавание' нет ни у кого

In [ ]:
prices = {"хлеб": 50, "молоко": 80, "яйца": 120, "сыр": 200, "колбаса": 300, "яблоки": 70, "бананы": 120}

print(f"Общая стоимость: {sum(prices.values())} руб.")

most_expensive = max(prices, key=prices.get)
print(f"Самый дорогой: {most_expensive} - {prices[most_expensive]} руб.")


cheap = [p for p, c in prices.items() if c < 100]
print(f"Продукты дешевле 100 руб.: {', '.join(cheap)}")

Общая стоимость: 940 руб.
Самый дорогой: колбаса - 300 руб.
Продукты дешевле 100 руб.: хлеб, молоко, яблоки

In [ ]:
point_a = (2, 5)
point_b = (8, 1)

length = abs(point_b[0] - point_a[0])
width = abs(point_b[1] - point_a[1])

print(f"Длина: {length}, Ширина: {width}")
print(f"Периметр: {2 * (length + width)}")
print(f"Площадь: {length * width}")

Длина: 6, Ширина: 4
Периметр: 20
Площадь: 24

In [ ]:
marks = input().split()

marks_from_map = list(map(int, marks))
marks_from_comprehension = [int(x) for x in marks]

marks_list = marks_from_comprehension

avg = sum(marks_list) / len(marks_list)

for m in marks_list:
    if m > avg:
        print(m)

Создать numpy-массив first размера 5 на 2 из чисел от 1 до 10 с помощью np.arange() и np.reshape.

Сделать массив second такой же формы из единиц с помощью np.ones_like.

Необходимо найти среднее по столбцам значение для суммы этих массивов. Результат суммы записывается в переменную sum_array.

In [ ]:
import numpy as np

first = np.arange(1, 11).reshape(5,2)

second = np.ones_like(first)

sum_array = first + second

sum_array.mean()

np.float64(6.5)

In [ ]:
for i in range(67):
  print("Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка")

Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка
Я очень сильно хочу себе малышку из ВШЭ, у которой голубые глаза и милая улыбка

Написать функцию roll_dice(), которая возвращает целое случайное число от 1 до 6. Для генерации случайного числа использовать функцию random.randint().

Сделать функцию print_result, которая принимает на вход число и печатает строку вида: "Случайное число - {аргумент_функции}", где {аргумент_функции} - значение аргумента функции

In [ ]:
import random

def roll_dice():
  return random.randint(1, 6)

def print_result(number: int):
  print(f"Случайное число - {number}")

1.5.2. Тренажер кода 2
На фабрике есть 3 производственных линии, выпускающие одинаковые телефоны.

Пользователь вводит для каждой линии долю телефонов, которую она выпускает (три числа через пробел, каждое число от 0 до 1, в сумме эти три числа дают 1).

Также пользователь вводит вероятность встретить брак телефона для каждой линии (три числа через пробел, каждое число от 0 до 1).

Необходимо написать программу, которая считает вероятность того, что случайно выбранный телефон окажется бракованным?

Пример ввода данных: 0.5 0.3 0.2 0.02 0.03 0.05

In [ ]:
df = pd.DataFrame({
    'name': ['Mike', 'Alice', 'Bob'],
    'age': [30, 40, 50],
    'job': ['Programmer', 'Analytists', 'Footbal manager']
})

In [ ]:
df

    name  age              job
0   Mike   30       Programmer
1  Alice   40       Analytists
2    Bob   50  Footbal manager

In [ ]:
df.loc[1]

name         Alice
age             40
job     Analytists
Name: 1, dtype: object

In [ ]:
df.set_index('name')

       age              job
name
Mike    30       Programmer
Alice   40       Analytists
Bob     50  Footbal manager

In [ ]:
df.iloc[1]

name         Alice
age             40
job     Analytists
Name: 1, dtype: object

In [ ]:
df.age * 2

0     60
1     80
2    100
Name: age, dtype: int64

In [ ]:
def my_function(x):
  if x % 3 == 0:
    return x**2
  else:
    return x // 2

In [ ]:
df.age.apply(my_function)

0    900
1     20
2     25
Name: age, dtype: int64

In [ ]:
def my_func2(x):
  if x.endswith('r'):
    return 'Without Job'
  else:
    x

In [ ]:
df.job.apply(my_func2)

0    Without Job
1           None
2    Without Job
Name: job, dtype: object

In [ ]:
df

    name  age              job
0   Mike   30       Programmer
1  Alice   40       Analytists
2    Bob   50  Footbal manager

Кейс 2. Умный помощник по учёбе



 Проблема:

 Школьники и студенты часто не успевают отслеживать дедлайны, запоминать, какие предметы нужно повторить, или что задали по домашнему. Использование ежедневников или заметок быстро становится неэффективным, а приложения требуют регистрации или наличия интернета.



 Решение:

 Разработка простого Python-приложения для учёта учебных задач. Каждая задача – это объект с предметом, датой, типом задания и приоритетом. Пользователь может добавлять задания, просматривать список, сортировать их по сроку или важности, фильтровать по предмету, отмечать выполненные. Реализация использует ООП, словари и списки. Это задание позволяет закрепить базовые принципы Python и развивает умение структурировать данные для реальных задач.

NameError: name 'StudyTask' is not defined